version: 2

# 依存関係のアップデートに関する設定
updates:
    # poetryの依存関係
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    # GitHub Actionsの依存関係
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

# 依存関係のアップデートがあった場合
# pull-requestを作成してお知らせ
