repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
  hooks:
  - id: commitizen
    stages:
      - commit-msg
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
  - id: poetry-check
    args: ["--lock"]
  - id: poetry-export
    args: ["--format", "requirements.txt", "--output", "requirements.txt"]
    verbose: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: detect-private-key
  # - id: check-added-large-files
  # args: ["--maxkb=500"]
  # - id: check-merge-conflict
  # - id: check-json
  # - id: check-toml
  # - id: check-yaml

  # - id: end-of-file-fixer
  # - id: trailing-whitespace
  # args: ["--markdown-linebreak-ext=md"]
