repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
  hooks:
  - id: commitizen
    stages:
      - commit-msg
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
  - id: poetry-check
    args: ["--lock"]
  - id: poetry-export
    args: ["--format", "requirements.txt", "--output", "requirements.txt"]
    verbose: true

