repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
    - id: commitizen
      stages:
        - commit-msg
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
    - id: poetry-check
      args: ["--lock"]
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]

