#+title:KumaROOT
#+author:しょーた

* まえがき

** ROOTのインストール

   MacPorts から簡単にインストールすることができます。
   ROOT5 と ROOT6 があるので、自分の用途にあったものをインストールしてください。
   variants に関しては適宜調べて指定してください。
   とりあえず使う場合は、特になくても良いと思います。

   ROOT6の場合は本当に気にしなくて良いと思いますが、
   ROOT5でPyROOTを使いたい場合は +python27 すると良いと思います。
   （もちろん、自分の使っているPythonのバージョンにしてください）

#+BEGIN_SRC bash
$ sudo port install root5 +python27
$ sudo port install root6
#+END_SRC

   MacPortsを使ってインストールした場合、port select で簡単に切り替えることができます。

#+BEGIN_SRC bash
$ port select --list root    # インストールされてるROOTを調べる
$ sudo port select --set root root6
#+END_SRC

*** ROOT5 と ROOT6 の違いについて

    CINTというROOTのインタプリタが変更されたみたいです。
    ROOT6の方がエラーの内容が詳しく表示されるので親切です。
    ただし、多くの実験ではROOT5を使っているケースが多いと思うので、
    自分の所属する環境に合わせて選択したら良いと思います。


** PyROOTのインストール

* 参考サイト
  - [[http://root.cern.ch/drupal/content/users-guide][ROOT公式ユーザーズガイド]] :: 困ったらとりあえず読む！
  - [[http://root.cern.ch/drupal/content/reference-guide][ROOT公式リファレンスガイド]] :: クラス名やそのメソッド名、内容、使い方を知りたい場合に使うべし！
  - [[http://root.cern.ch/root/html/tutorials/][ROOT公式チュートリアル]] :: 付属のサンプルコードを試すべし！
  - [[http://root.cern.ch/drupal/content/c-coding-conventions][ROOT公式コーディングガイド]] :: ROOTのソースコードを読むときに役に立つかも
  - [[http://hep.planet-koo.com/index.php?g=root][ROOT解体新書]] by 楠本さん :: gROOTとか、gStyleの設定など、他のページ／マニュアルでは見られない項目がすごく詳しい

* 全体設定編
** キャンバスを無地にしたい
** 統計情報を表示したい
** フィットの結果を表示したい
** ヒストグラムの線の太さを一括で変更したい
** デフォルトの色を変更したい
** 横軸に時間を使いたい
** キャンバスに補助線を描きたい
** グラフの軸を一括してログ表示にする
** 軸の目盛り間隔を変更したい
* ヒストグラム編
* TTree編
* TChain編
* TFile編
* TCanvas編
* TLegend編
* TString編
