#+title:KumaROOT
#+author:しょーた

* はじめに

  これまで古巣の研究室に設置したDokuWikiにROOTなどの情報を書きためてい
  ましたが、そろそろ引っ越しをしなくてはいけない ＋ せっかく書きためた
  ものを残しておきたいと思い、GitHubにて公開することにしました。

  「くまROOT」と名づけたのは、私がROOTを使い始めたときに、最初に目を通
  した「猿にも使えるROOT」（通称：さるROOT）の知名度にあやかりたかった
  ためです。

  「さる」の次は「くま」を読んでもらえるように頑張りたいと思います。



  また、GitHubで公開するということで、動作するサンプルコードも作成して
  いこうと思います。



  読者は、ちょっとだけROOTを使ったことがある
  学生を対象にします。そして逆引き辞典として使えるようにしたいと思いま
  す。


* ROOTを使いたい

  最近のROOTはとても簡単にインストールできるようになっています。Macを
  使っている場合は、MacPortsというパッケージ管理ソフトからインストール
  することができます。

#+begin_src bash
$ sudo port install root    ## 実際にはroot5 がインストールされる
#+end_src

** ROOT6を使いたい

   2014年にROOT6がリリースされました。MacPortsを調べてみると、root6と
   いうのがあるので、そちらをインストールします。

#+begin_src bash
$ sudo port install root6
#+end_src

** ROOT5 と ROOT6 を試してみたい

   MacPortsでROOTをインストールする利点は、ROOT5 と ROOT6 が簡単に切り
   替えられることです。

#+BEGIN_SRC bash
$ sudo port select --set root root6   ## ROOT6にする
$ sudo port select --set root root5   ## ROOT5にする
#+END_SRC

   実はこの「port select」はPythonのバージョン切り替えなどもできます。
   どのパッケージが使えるかは以下のコマンドで確認できます

#+begin_src bash
$ port select --summary
#+end_src

*** ROOT5 と ROOT6 の違いについて

    ざっくりいうとROOTのインタプリタが変更されたみたいです（CINT ->
    CINT++に変更）。文法のチェックが厳密になりました。

    実はROOT5では文法的に間違っているマクロでも動いてくれました。その
    ため、テストで作ったマクロで動作確認した後、より多くのデータ解析の
    ためにコンパイルするとエラーが多出。そのデバッグに追われるというこ
    とは日常茶飯事でした。

    ROOT6では、マクロの文法チェックが厳しくなったみたいです。ひぇぇ。
    でも心配しなくて大丈夫です。エラーの内容を詳しく教えてくれるように
    なりました。よくある行末のセミコロンのつけ忘れなども指摘してくれま
    す。場所の分からない segmentation fault に悩まされることも減るでしょ
    う。


** PyROOTを使いたい

   CERNにはへび使いが多いようで、ROOTもPythonから使えるようになっています。
   「PyROOT」というこのラッパーを使うには、pythonのオプション
   （variants）を付けてインストールする必要があります。

#+begin_src bash
$ sudo port install root5 +python27   ## ROOT5の場合は variants が必要
$ sudo port install root6             ## ROOT6の場合、実は variants 不要
#+END_SRC




* 参考サイト
  - [[http://root.cern.ch/drupal/content/users-guide][ROOT公式ユーザーズガイド]] :: 困ったらとりあえず読む！
  - [[http://root.cern.ch/drupal/content/reference-guide][ROOT公式リファレンスガイド]] :: クラス名やそのメソッド名、内容、使い方を知りたい場合に使うべし！
  - [[http://root.cern.ch/root/html/tutorials/][ROOT公式チュートリアル]] :: 付属のサンプルコードを試すべし！
  - [[http://root.cern.ch/drupal/content/c-coding-conventions][ROOT公式コーディングガイド]] :: ROOTのソースコードを読むときに役に立つかも
  - [[http://hep.planet-koo.com/index.php?g=root][ROOT解体新書]] by 楠本さん :: gROOTとか、gStyleの設定など、他のページ／マニュアルでは見られない項目がすごく詳しい

* 全体設定編
** キャンバスを無地にしたい
** 統計情報を表示したい
** フィットの結果を表示したい
** ヒストグラムの線の太さを一括で変更したい
** デフォルトの色を変更したい
** 横軸に時間を使いたい
** キャンバスに補助線を描きたい
** グラフの軸を一括してログ表示にする
** 軸の目盛り間隔を変更したい
* ヒストグラム編
* TTree編
* TChain編
* TFile編
* TCanvas編
* TLegend編
* TString編
