# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  docs:
    desc: Start Sphinx livehtml
    dir: docs
    cmds:
      - uv run make livehtml

  code:
    desc: Start VS Code
    cmds:
      - uv run code .

  outdated:
    desc: Show outdated packages
    cmds:
      - uv pip list --outdated

  update:
    desc: Update dependencies
    cmds:
      - uv sync --upgrade --all-extras

  sync:
    desc: Sync dependencies from lockfile
    cmds:
      - uv sync --all-extras

  pre-commit:
    desc: Run pre-commit hooks on all files
    cmds:
      - uv run pre-commit run --all-files

  # ============================================================
  # Version management tasks - Manage versions with commitizen
  # ============================================================

  bump:check:
    desc: Preview next version bump
    cmds:
      - echo "Preview of next version bump"
      - uv run cz bump --check-consistency --changelog --dry-run

  bump:patch:
    desc: Bump patch version. Use this daily.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment patch

  bump:minor:
    desc: Bump minor version. Use once when the month changed.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment minor

  bump:major:
    desc: Bump major version. Use once when the year changed.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment major
