# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  livehtml:
    desc: Start Sphinx livehtml
    dir: docs
    cmds:
      - poetry run make livehtml

  code:
    desc: Start VS Code
    cmds:
      - poetry run code .

  export:
    desc: Export requirements.txt
    cmds:
      - poetry export --output requirements.txt

  update:
    desc: Update dependencies
    cmds:
      - poetry update
      - task: export
