# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  docs:
    desc: Start Sphinx livehtml
    dir: docs
    cmds:
      - uv run make livehtml

  code:
    desc: Start VS Code
    cmds:
      - uv run code .

  export:
    desc: Export requirements.txt for Read the Docs
    cmds:
      - uv pip compile pyproject.toml -o requirements.txt --all-extras

  outdated:
    desc: Show outdated packages
    cmds:
      - uv pip list --outdated

  update:
    desc: Update dependencies
    cmds:
      - uv sync --upgrade --all-extras
      - task: export

  sync:
    desc: Sync dependencies from lockfile
    cmds:
      - uv sync --all-extras

  bump:
    desc: Bump patch version with commitizen
    cmds:
      - uv run cz bump --increment PATCH

  bump:minor:
    desc: Bump minor version with commitizen
    cmds:
      - uv run cz bump --increment MINOR

  changelog:
    desc: Generate changelog with commitizen (incremental)
    cmds:
      - uv run cz changelog --incremental

  pre-commit:
    desc: Run pre-commit hooks on all files
    cmds:
      - uv run pre-commit run --all-files
