# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  livehtml:
    desc: Start Sphinx livehtml
    dir: docs
    cmds:
      - poetry run make livehtml

  code:
    desc: Start VS Code
    cmds:
      - poetry run code .

  export:
    desc: Export requirements.txt
    cmds:
      - poetry export --output requirements.txt

  outdated:
    desc: Show outdated packages
    cmds:
      - poetry show --outdated

  update:
    desc: Update dependencies
    cmds:
      - poetry update
      - task: export

  bump:patch:
    desc: Bump patch version with commitizen
    cmds:
      - poetry run cz bump --patch

  bump:minor:
    desc: Bump minor version with commitizen
    cmds:
      - poetry run cz bump --minor
