# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list
      - task: status
    silent: true

  code:
    desc: Start VS Code
    cmds:
      - uv run code .

  # ============================================================================
  # Pre-commit Hooks
  # ============================================================================

  pre-commit:setup:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install
      - echo "Pre-commit hooks installed"
    silent: true

  pre-commit:
    desc: Run pre-commit hooks on all files
    cmds:
      - uv run pre-commit run --all-files
      - git status

  pre-commit:update:
    desc: Update pre-commit hooks to latest versions
    cmds:
      - uv run pre-commit autoupdate
      - echo "Pre-commit hooks updated"
    silent: true

  pre-commit:uninstall:
    desc: Uninstall pre-commit hooks
    cmds:
      - uv run pre-commit uninstall
      - echo "Pre-commit hooks uninstalled"
    silent: true

  # ============================================================================
  # Documentation tasks
  # ============================================================================

  docs:serve:
    desc: Preview docs locally (sphinx-autobuild)
    dir: docs
    cmds:
      - uv run make livehtml

  docs:build:
    desc: Build docs as static HTML
    dir: docs
    cmds:
      - uv run make livehtml

  docs:pdf:
    desc: Build docs as PDF
    dir: docs
    cmds:
      - uv run make latexpdf

  # ============================================================================
  # Dependency management tasks - Update and check dependencies
  # ============================================================================

  deps:setup:
    desc: Setup Python environment
    cmds:
      - uv sync --all-extras

  deps:check:
    desc: Check for outdated packages
    cmds:
      - uv pip list --outdated

  deps:update:
    desc: Update dependencies
    cmds:
      - uv sync --upgrade --all-extras

  # ============================================================================
  # Version management tasks - Manage versions with commitizen
  # ============================================================================

  version:
    desc: Show current version
    cmds:
      - git tag -l | sort -V | tail -n 1
    silent: true

  bump:check:
    desc: Preview next version bump (dry-run)
    cmds:
      - echo "Preview of next version bump"
      - uv run cz bump --check-consistency --changelog --dry-run

  bump:patch:
    desc: Bump patch version. Use this daily.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment patch

  bump:minor:
    desc: Bump minor version. Use once when the month changed.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment minor

  bump:major:
    desc: Bump major version. Use once when the year changed.
    cmds:
      - uv run cz bump --check-consistency --changelog --increment major

  # ============================================================================
  # Git management tasks - Manage Git
  # ============================================================================

  status:
    desc: Show git status
    cmds:
      - git status

  log:
    desc: Show recent commits (last 10)
    cmds:
      - git log --oneline -10

  push:
    desc: Push commits to remote (main branch)
    cmds:
      - git push origin main

  push:tags:
    desc: Push commits and tags to remote
    cmds:
      - git push origin main --tags
