$pdf_mode = 4;
# @default_files = ("ファイル1", "ファイル2");
$preview_continuous_mode = 1;
$pvc_timeout = 1;
$pvc_timeout_mins = 10;  # 30min; default
$sleep_time = 10;  # 60s
# $out_dir = "outd";
# $aux_dir = "auxd";
