# https://hub.docker.com/_/httpd
#
# docker container run -d -p 8080:80 httpd:2.4 に相当
#
# $ docker compose up --detach
# $ open http://127.0.0.1:8080/
# $ docker compose down --volumes
services:
  web:
    image: httpd:2.4
    ports:
      - 8080:80
