# -*- coding: utf-8 -*-
#
# KumaROOT documentation build configuration file, created by
# sphinx-quickstart on Sat Jul 11 17:44:03 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import sphinx_rtd_theme

##################################################
## Project information
##################################################

project = 'KumaROOT'
author = 'Shota TAKAHASHI'
copyright = '2015, Shota TAKAHASHI'
version = '0.3.0'
release = '0.3.0'

##################################################
## General configuration
##################################################

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx_rtd_theme',
]

source_suffix = {'.rst': 'restructuredtext'}
source_encoding = 'utf-8-sig'
master_doc = 'index'
exclude_patterns = []
templates_path = ['_templates']
numfig = True
pygments_style = 'sphinx'

##################################################
## Options for i18n
##################################################
language = 'ja'

#################################################
## Options for sphinx.ext.todo
##################################################
todo_include_todos = True


# 'figure', 'table', 'code-block' に対して
# それぞれ図表番号表示のためのフォーマット文字列を
# 指定する辞書です。(バージョン 1.3 で追加)
numfig_format = {
    'figure' : u'Fig. %s',
    'table' : u'Table %s',
    'code-block' : u'Listing %s'
}
numfig_format['figure'] = u'図 %s'
numfig_format['table'] = u'表 %s'
numfig_format['code-block'] = u'リスト %s'

# 図表番号のスコープです。
# スコープ指定によって、numfig機能が番号付けする範囲を決めます。
# 0 は全てのドキュメントで通し番号を使います。
# 1 はセクション毎の番号付けで、x.1, x.2, x.3, ...のように付与します。
# 2 はサブセクション毎の番号付けで、x.x.1, x.x.2, x.x.3, ...のように付与します。
# デフォルトは 1 です。
numfig_secnum_depth = 1

##################################################
## Options for HTML
##################################################

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'navigation_depth': 4,
}
#html_theme_path = []
#html_title = None
#html_short_title = None
#html_logo = None
#html_favicon = None
html_static_path = ['_static']
#html_extra_path = []
#html_last_updated_fmt = '%b %d, %Y'
#html_use_smartypants = True
#html_sidebars = {}
#html_additional_pages = {}
#html_domain_indices = True
#html_use_index = True
#html_split_index = False
#html_show_sourcelink = True
#html_show_sphinx = True
#html_show_copyright = True
#html_use_opensearch = ''
#html_file_suffix = None
html_search_language = 'ja'
#html_search_options = {'type': 'default'}
#html_search_scorer = 'scorer.js'
htmlhelp_basename = 'KumaROOTdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',
    'papersize' : 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',
    'pointsize': '12pt',

# Additional stuff for the LaTeX preamble.
    'preamble': '',

# Latex figure (float) alignment
    'figure_align': 'htbp',

#    'fontpkg': '\\usepackage{times}',

}

latex_elements['preamble'] += '\\usepackage{pxjahyper}\n'
latex_elements['preamble'] += '\\usepackage{graphics}\n'
latex_elements['preamble'] += '\\hypersetup{bookmarksnumbered=true}\n'
latex_elements['preamble'] += '\\hypersetup{bookmarksopen=true}\n'
latex_elements['preamble'] += '\\hypersetup{bookmarksopenlevel=2}\n'
latex_elements['preamble'] += '\\hypersetup{colorlinks=true}\n'
latex_elements['preamble'] += '\\hypersetup{pdfpagemode=UseOutlines}\n'

# latex_elements['preamble'] += '\\renewcommand{\\familydefault}{\\sfdefault}\n'
# latex_elements['preamble'] += '\\renewcommand{\\kanjifamilydefault}{\\gtdefault}\n'




# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#   (master_doc, 'KumaROOT.tex', u'KumaROOT Documentation',
#    u'Shota TAKAHASHI', 'manual'),
# ]
latex_documents = [
  (master_doc, 'KumaROOT.tex', u'KumaROOT Documentation',
   u'Shota TAKAHASHI', 'manual'),
]
latex_docclass = {'manual' : 'jsbook'}
#latex_docclass = {'manual' : 'bxjsreport'}

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = './images/toumin_kuma.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'kumaroot', u'KumaROOT Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  (master_doc, 'KumaROOT', u'KumaROOT Documentation',
   author, 'KumaROOT', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
#epub_basename = project

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}
